user_name_max_length: 50
email_max_length: 255
password_min_length: 6
remember_status: 1
paginate_users: 20
gravatar_size: 50
gravatar_option_size: 80
ENV_prod_address: "smtp.sendgrid.net"
ENV_prod_port: "587"
ENV_prod_domain: "heroku.com"
password_reset_expired: 1
paginate_microposts: 10
micropost_content_max_length: 140
micropost_picture_size: 5
user_micropost_gravatar_size: 50
user_micropost_picture_types: "image/jpeg,image/gif,image/png"
